version: '3.8'

services:
  reset-app:
    container_name: web-reset-container
    build:
      context: .
      dockerfile: Dockerfile
      # PENTING: Mengirim value dari file .env ke Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY: ${VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY}
        VITE_APP_NAME: ${VITE_APP_NAME}
        APP_STORE_URL: ${APP_STORE_URL}
        PLAY_STORE_URL: ${PLAY_STORE_URL}
    restart: unless-stopped
    ports:
      - "80:80"
    # Membaca file .env
    env_file:
      - .env